language: java

jdk:
  - openjdk14

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="b379e05c-57dd-44ed-bf8c-c61a7bc9e9a1"

notifications:
  email:
    recipients:
      - anatoliy.gromov.service@gmail.com
    on_success: never # default: change
    on_failure: always # default: always